"""Add google_id to user

Revision ID: f5a7b9c12345
Revises: d98dd8ec85a3
Create Date: 2025-08-13 10:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5a7b9c12345"
down_revision = "d98dd8ec85a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True)
    )
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###